FROM 388813176377.dkr.ecr.us-east-1.amazonaws.com/office_desk_reservations_base:base_project

# Copy function code to container
COPY desk_reservation/bookings/infrastructure/controllers/find_booking.py ./

# setting the CMD
CMD ["find_booking.find_booking_controller"]
