# python3.9 lambda base image
FROM public.ecr.aws/lambda/python:3.9.2022.09.09.11

# copy requirements.txt to container
COPY poetry.lock ./
COPY pyproject.toml ./

# Installing dependencies
RUN pip install poetry
RUN poetry install

ADD base.tar .

# Tag as base image