# python3.9 lambda base image
FROM public.ecr.aws/lambda/python:3.9.2022.09.09.11

# copy requirements.txt to container
COPY requirements.txt ./

# Installing dependencies
RUN pip install -r requirements.txt

ADD base.tar .

# Tag as base image
