name: DELETE SHORT RESERVATIONS
# Controls when the workflow will run
on:
  schedule: # “Every 5 minutes”
    - cron: "*/5 * * * *"
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: INSTALL FIREBASE
        run: |
          npm install firebase
      - name: RUN CRONJOB
        run: |
          npm run job